package mx.posadev.response

data class OrganizationResponse(
        val login: String,
        val id: Long,
        val url: String,
        val reposUrl: String,
        val eventsUrl: String,
        val hooksUrl: String,
        val issuesUrl: String,
        val membersUrl: String,
        val publicMembersUrl: String,
        val avatarUrl: String,
        val description: String?,
        val name: String?,
        val company: String?,
        val blog: String,
        val location: String?,
        val email: String?,
        val hasOrganizationProjects: Boolean,
        val hasRepositoryProjects: Boolean,
        val publicRepos: Int,
        val publicGists: Int,
        val followers: Long,
        val following: Long,
        val htmlUrl: String,
        val createdAt: String,
        val updatedAt: String,
        val type: String) : Response