package mx.posadev.response

data class UserResponse(
        val login: String,
        val id: Long = 0,
        val avatarUrl: String? = "",
        val gravatarId: String? = "",
        val url: String? = "",
        val htmlUrl: String? = "",
        val followersUrl: String? = "",
        val followingUrl: String? = "",
        val gistsUrl: String? = "",
        val starredUrl: String? = "",
        val subscriptionsUrl: String? = "",
        val organizationsUrl: String? = "",
        val reposUrl: String? = "",
        val eventsUrl: String? = "",
        val receivedEventsUrl: String? = "",
        val type: String? = "",
        val isSiteAdmin: Boolean = false,
        val name: String? = "",
        val company: String? = "",
        val blog: String? = "",
        val location: String? = "",
        val email: String? = "",
        val isHireable: Boolean = false,
        val bio: String? = "",
        val publicRepos: Long = 0,
        val publicGists: Long = 0,
        val followers: Long = 0,
        val following: Long = 0,
        val createdAt: String? = "",
        val updatedAt: String? = "") : Response